name: Post welcome comment
on:
  pull_request:
    types: [opened]
jobs:
  build:
    name: post welcome comment 
    run-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "welcome to the respository!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
